
export const GET_CATEGORY_START = 'GET_CATEGORY_START';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';

export const GET_QUESTIONARY_START = 'GET_QUESTIONARY_START';
export const GET_QUESTIONARY_SUCCESS = 'GET_QUESTIONARY_SUCCESS';
export const GET_QUESTIONARY_FAIL = 'GET_QUESTIONARY_FAIL';